# Container image
image: node:slim

# Stages
stages:
  - setup
  - build
  - test
  - release

variables:
  GITLAB_TOKEN: $GL_TOKEN

# Release new version
create-release:
  image: node:lts-alpine3.14
  # tags:
  #   - changani
  stage: release
  before_script:
    - apk --no-cache add git
    - npm i @semantic-release/changelog @semantic-release/git @semantic-release/gitlab
    - npx husky install
    - npx husky add .husky/commit-msg 'npx --no-install commitlint --edit $1'
  script: npx semantic-release
  only:
    refs:
      - main
