name: CI
on:
  push:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

  trigger-release:
    if: github.ref == 'refs/heads/main'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Release
        run: curl -v -H "Accept:\ application/vnd.github.everest-preview+json" -H "Authorization:\ token ${GITHUB_TOKEN}" https://api.github.com/repos/flowck/coingecko-dashboard-copycat-react/dispatches -d '{ "event_type":\ "semantic-release" }'
