name: Release
on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Release
        uses: ridedott/release-me-action@master
